config/routes.rb
Telangana::Application.routes.draw do
  resources :user_profiles

  devise_for :mps
  devise_for :mlas
  get "static/home"
  get "static/about"
  get "static/contact"
  root 'static#home'

  resources :fb_tokens

  resources :villages

  devise_for :politicians
  resources :constitutions

  resources :districts

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :slogans

  resources :groups

  resources :pages

  devise_for :users

end

app/models/constitution.rb
class Constitution < ActiveRecord::Base
	include RailsAdminCharts

	belongs_to :district
  #district_id :integer
  
	has_many :villages
  has_many :groups
  has_many :pages
  has_many :users
  has_many :user_profiles
end

app/models/district.rb
class District < ActiveRecord::Base

	include RailsAdminCharts

	 def self.xaxis
    ['cat a', 'cat b', 'cat c' 'cat d', 'cat e', 'cat f', 'cat g', 'cat h']
   end
    def self.label_rotation
    "-45"
  end
	has_many :constitutions
end

app/models/fb_token.rb
class FbToken < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base

	include RailsAdminCharts

	belongs_to :constitution

	#constitution_id 
end

app/models/mla.rb
class Mla < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/mp.rb
class Mp < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/page.rb
class Page < ActiveRecord::Base
	include RailsAdminCharts

		belongs_to :constitution 
		#constitution_id
end

app/models/politician.rb
class Politician < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/slogan.rb
class Slogan < ActiveRecord::Base
	include RailsAdminCharts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable

  # attr_accessible :provider,:uid,:username
  
  #relations 
  belongs_to :constitution
  #
  
  #fb ouath scope
  def self.find_for_facebook_oauth(auth)
   where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base

	belongs_to :constitution
end

app/models/village.rb
class Village < ActiveRecord::Base

	include RailsAdminCharts


    belongs_to :constitution
  
  	has_many :groups
  	has_many :pages

end

app/controllers/constitutions_controller.rb
class ConstitutionsController < ApplicationController
  before_action :set_constitution, only: [:show, :edit, :update, :destroy]

  # GET /constitutions
  # GET /constitutions.json
  def index
    @constitutions = Constitution.all
  end

  # GET /constitutions/1
  # GET /constitutions/1.json
  def show
  end

  # GET /constitutions/new
  def new
    @constitution = Constitution.new
  end

  # GET /constitutions/1/edit
  def edit
  end

  # POST /constitutions
  # POST /constitutions.json
  def create
    @constitution = Constitution.new(constitution_params)

    respond_to do |format|
      if @constitution.save
        format.html { redirect_to @constitution, notice: 'Constitution was successfully created.' }
        format.json { render action: 'show', status: :created, location: @constitution }
      else
        format.html { render action: 'new' }
        format.json { render json: @constitution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constitutions/1
  # PATCH/PUT /constitutions/1.json
  def update
    respond_to do |format|
      if @constitution.update(constitution_params)
        format.html { redirect_to @constitution, notice: 'Constitution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @constitution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constitutions/1
  # DELETE /constitutions/1.json
  def destroy
    @constitution.destroy
    respond_to do |format|
      format.html { redirect_to constitutions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constitution
      @constitution = Constitution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def constitution_params
      params.require(:constitution).permit(:c_id, :name,:district_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @page }
      else
        format.html { render action: 'new' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constitutions_helper.rb
module ConstitutionsHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/fb_tokens_helper.rb
module FbTokensHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/slogans_helper.rb
module SlogansHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/constitutions/_form.html.erb
<%= form_for(@constitution) do |f| %>
  <% if @constitution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constitution.errors.count, "error") %> prohibited this constitution from being saved:</h2>

      <ul>
      <% @constitution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :c_id %><br>
    <%= f.text_field :c_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/constitutions/edit.html.erb
<h1>Editing constitution</h1>

<%= render 'form' %>

<%= link_to 'Show', @constitution %> |
<%= link_to 'Back', constitutions_path %>

app/views/constitutions/index.html.erb
<h1>Listing constitutions</h1>

<table>
  <thead>
    <tr>
      <th>C</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @constitutions.each do |constitution| %>
      <tr>
        <td><%= constitution.c_id %></td>
        <td><%= constitution.name %></td>
        <td><%= link_to 'Show', constitution %></td>
        <td><%= link_to 'Edit', edit_constitution_path(constitution) %></td>
        <td><%= link_to 'Destroy', constitution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Constitution', new_constitution_path %>

app/views/constitutions/new.html.erb
<h1>New constitution</h1>

<%= render 'form' %>

<%= link_to 'Back', constitutions_path %>

app/views/constitutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>C:</strong>
  <%= @constitution.c_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @constitution.name %>
</p>

<%= link_to 'Edit', edit_constitution_path(@constitution) %> |
<%= link_to 'Back', constitutions_path %>