config/routes.rb
Telangana::Application.routes.draw do
  resources :user_profiles

  devise_for :mps
  devise_for :mlas
  get "static/home"
  get "static/about"
  get "static/contact"
  root 'static#home'

  resources :fb_tokens

  resources :villages

  devise_for :politicians
  resources :constitutions

  resources :districts

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :slogans

  resources :groups

  resources :pages

  devise_for :users

end

app/models/constitution.rb
class Constitution < ActiveRecord::Base
	include RailsAdminCharts

	belongs_to :district
  #district_id :integer
  
	has_many :villages
  has_many :groups
  has_many :pages
  has_many :users
  has_many :user_profiles
end

app/models/district.rb
class District < ActiveRecord::Base

	include RailsAdminCharts

	 def self.xaxis
    ['cat a', 'cat b', 'cat c' 'cat d', 'cat e', 'cat f', 'cat g', 'cat h']
   end
    def self.label_rotation
    "-45"
  end
	has_many :constitutions
end

app/models/fb_token.rb
class FbToken < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base

	include RailsAdminCharts

	belongs_to :constitution

	#constitution_id 
end

app/models/mla.rb
class Mla < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/mp.rb
class Mp < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/page.rb
class Page < ActiveRecord::Base
	include RailsAdminCharts

		belongs_to :constitution 
		#constitution_id
end

app/models/politician.rb
class Politician < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/slogan.rb
class Slogan < ActiveRecord::Base
	include RailsAdminCharts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable

  # attr_accessible :provider,:uid,:username
  
  #relations 
  belongs_to :constitution
  #
  
  #fb ouath scope
  def self.find_for_facebook_oauth(auth)
   where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base

	belongs_to :constitution
end

app/models/village.rb
class Village < ActiveRecord::Base

	include RailsAdminCharts


    belongs_to :constitution
  
  	has_many :groups
  	has_many :pages

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @page }
      else
        format.html { render action: 'new' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :id)
    end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:name, :fbprofile_id, :refernces)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/fb_tokens_helper.rb
module FbTokensHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/slogans_helper.rb
module SlogansHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/user_profiles/_form.html.erb
<%= form_for(@user_profile) do |f| %>
  <% if @user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% @user_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :fbprofile_id %><br>
    <%= f.text_field :fbprofile_id %>
  </div>
  <div class="field">
    <%= f.label :refernces %><br>
    <%= f.text_field :refernces %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<h1>Listing user_profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fbprofile</th>
      <th>Refernces</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.name %></td>
        <td><%= user_profile.fbprofile_id %></td>
        <td><%= user_profile.refernces %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New user_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_profile.name %>
</p>

<p>
  <strong>Fbprofile:</strong>
  <%= @user_profile.fbprofile_id %>
</p>

<p>
  <strong>Refernces:</strong>
  <%= @user_profile.refernces %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>