config/routes.rb
Telangana::Application.routes.draw do
  resources :user_profiles

  devise_for :mps
  devise_for :mlas
  get "static/home"
  get "static/about"
  get "static/contact"
  root 'static#home'

  resources :fb_tokens

  resources :villages

  devise_for :politicians
  resources :constitutions

  resources :districts

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :slogans

  resources :groups

  resources :pages

  devise_for :users

end

app/models/constitution.rb
class Constitution < ActiveRecord::Base
	include RailsAdminCharts

	belongs_to :district
  #district_id :integer
  
	has_many :villages
  has_many :groups
  has_many :pages
  has_many :users
  has_many :user_profiles
end

app/models/district.rb
class District < ActiveRecord::Base

	include RailsAdminCharts

	 def self.xaxis
    ['cat a', 'cat b', 'cat c' 'cat d', 'cat e', 'cat f', 'cat g', 'cat h']
   end
    def self.label_rotation
    "-45"
  end
	has_many :constitutions
end

app/models/fb_token.rb
class FbToken < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base

	include RailsAdminCharts

	belongs_to :constitution

	#constitution_id 
end

app/models/mla.rb
class Mla < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/mp.rb
class Mp < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/page.rb
class Page < ActiveRecord::Base
	include RailsAdminCharts

		belongs_to :constitution 
		#constitution_id
end

app/models/politician.rb
class Politician < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/slogan.rb
class Slogan < ActiveRecord::Base
	include RailsAdminCharts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable

  # attr_accessible :provider,:uid,:username
  
  #relations 
  belongs_to :constitution
  #
  
  #fb ouath scope
  def self.find_for_facebook_oauth(auth)
   where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base

	belongs_to :constitution
end

app/models/village.rb
class Village < ActiveRecord::Base

	include RailsAdminCharts


    belongs_to :constitution
  
  	has_many :groups
  	has_many :pages

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @page }
      else
        format.html { render action: 'new' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :id)
    end
end

app/controllers/slogans_controller.rb
class SlogansController < ApplicationController
  before_action :set_slogan, only: [:show, :edit, :update, :destroy]

  # GET /slogans
  # GET /slogans.json
  def index
    @slogans = Slogan.all
  end

  # GET /slogans/1
  # GET /slogans/1.json
  def show
  end

  # GET /slogans/new
  def new
    @slogan = Slogan.new
  end

  # GET /slogans/1/edit
  def edit
  end

  # POST /slogans
  # POST /slogans.json
  def create
    @slogan = Slogan.new(slogan_params)

    respond_to do |format|
      if @slogan.save
        format.html { redirect_to @slogan, notice: 'Slogan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @slogan }
      else
        format.html { render action: 'new' }
        format.json { render json: @slogan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slogans/1
  # PATCH/PUT /slogans/1.json
  def update
    respond_to do |format|
      if @slogan.update(slogan_params)
        format.html { redirect_to @slogan, notice: 'Slogan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slogan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slogans/1
  # DELETE /slogans/1.json
  def destroy
    @slogan.destroy
    respond_to do |format|
      format.html { redirect_to slogans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slogan
      @slogan = Slogan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slogan_params
      params.require(:slogan).permit(:name, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constitutions_helper.rb
module ConstitutionsHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/fb_tokens_helper.rb
module FbTokensHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/slogans_helper.rb
module SlogansHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/slogans/_form.html.erb
<%= form_for(@slogan) do |f| %>
  <% if @slogan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slogan.errors.count, "error") %> prohibited this slogan from being saved:</h2>

      <ul>
      <% @slogan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slogans/edit.html.erb
<h1>Editing slogan</h1>

<%= render 'form' %>

<%= link_to 'Show', @slogan %> |
<%= link_to 'Back', slogans_path %>

app/views/slogans/index.html.erb
<h1>Listing slogans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @slogans.each do |slogan| %>
      <tr>
        <td><%= slogan.name %></td>
        <td><%= slogan.content %></td>
        <td><%= slogan.user_id %></td>
        <td><%= link_to 'Show', slogan %></td>
        <td><%= link_to 'Edit', edit_slogan_path(slogan) %></td>
        <td><%= link_to 'Destroy', slogan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slogan', new_slogan_path %>

app/views/slogans/new.html.erb
<h1>New slogan</h1>

<%= render 'form' %>

<%= link_to 'Back', slogans_path %>

app/views/slogans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slogan.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @slogan.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @slogan.user_id %>
</p>

<%= link_to 'Edit', edit_slogan_path(@slogan) %> |
<%= link_to 'Back', slogans_path %>